### ISSUE TITLE
no hosts matched when use group weed_master, weed_volume and weed_filer

### ISSUE THREAD

**Issue by patsevanton** [bmillemathias/ansible-role-seaweedfs#11]
Hello! Thanks for role!
I try install seaweedfs on multiple nodes and get **no hosts matched**
Inventory:
```
[weed_master]
51.250.17.31
[weed_volume]
51.250.17.31
[weed_filer]
51.250.17.31
[all:vars]
ansible_user=ubuntu
```

Playbook
```
---
- hosts: seaweedfs
  become: true
  roles:
    - role: ansible-role-seaweedfs
      weed_version: 2.74
```

Run:
```
ansible-galaxy install --force git+https://github.com/bmillemathias/ansible-role-seaweedfs.git,main
ansible-playbook -i host.ini playbook.yml -bK
```

**Comment by patsevanton** [comment]
When use inventory with group all then get **no hosts matched**
```
[all]
51.250.17.31
[all:vars]
ansible_user=ubuntu
```

**Comment by grozadanut** [comment]
I believe it's because you don't have the seaweedfs group. Change your playbook to:

```
---
- hosts: all
  become: true
  roles:
    - role: ansible-role-seaweedfs
      weed_version: 2.74
```
