### ISSUE TITLE
Default variables can't be overridden

### ISSUE THREAD

**Issue by egguy** [bmillemathias/ansible-role-seaweedfs#12]
Hi,

I'm trying to use the role, and it seems there are some problems with the variables.
I want to use a version defined in the all vars, like thus:

```yaml
weed:
  version: '2.99'
```

But it's not taken into account, the only way is to put :

```yaml
input:
  version: '2.99'
```
I've also tried the weed_version, but it's not working either.

It seems the problem come from this line:https://github.com/bmillemathias/ansible-role-seaweedfs/blob/eb773b2fa8c3c5cd77f4d6c9e9aac4f314b5142d/tasks/main.yml#L4

Perhaps I'm missing something.

Thx for the role

**Comment by washcycle** [comment]
You need the a `-` in from of version and then it should work.
```
input:
  - version: '2.99'
    large_disk: false
    ....
roles:
  - role: ansible-role-seaweedfs      
```
